"""Local setup helper.

The app refuses to start without its secrets, by design. This generates them
into a .env that is gitignored, so a fresh clone is one command from running
without ever tempting anyone to hardcode a default.
"""

from __future__ import annotations

import base64
import secrets
import sys
from pathlib import Path

from .config import REPO_ROOT

ENV_PATH = REPO_ROOT / ".env"

TEMPLATE = """\
# Generated by `uv run stegoshare-init`. Never commit this file.

STEGOSHARE_ENV=development
STEGOSHARE_DEBUG=0

# Flask session signing key.
STEGOSHARE_SECRET_KEY={secret_key}

# Key-encryption key: wraps every per-share data key. Losing it makes every
# stored file permanently unreadable. Rotating it means re-wrapping every row
# in `grants`, which never touches the stored ciphertext.
STEGOSHARE_FILE_KEK={file_kek}

# Local development storage.
STEGOSHARE_STORAGE=local
STEGOSHARE_DB_PATH={db_path}
STEGOSHARE_STORAGE_PATH={storage_path}

# --- object storage for hosting -------------------------------------------
# Install the extra first:  uv sync --extra s3
# The bucket must be private. Credentials are NOT set here -- boto3 resolves
# them from the environment, an instance role, or a profile, so a deployed
# instance can use a role and hold no long-lived key at all.
#
# STEGOSHARE_STORAGE=s3
# STEGOSHARE_S3_BUCKET=stegoshare-objects
# STEGOSHARE_S3_PREFIX=objects
# STEGOSHARE_S3_REGION=us-east-1
#
# For MinIO or Cloudflare R2, point the endpoint at the service:
# STEGOSHARE_S3_ENDPOINT=http://127.0.0.1:9000
#
# Defence in depth only -- objects are already encrypted before upload:
# STEGOSHARE_S3_SSE=AES256
"""


def init() -> int:
    if ENV_PATH.exists():
        print(f"{ENV_PATH} already exists. Delete it first to regenerate.",
              file=sys.stderr)
        return 1

    ENV_PATH.write_text(
        TEMPLATE.format(
            secret_key=secrets.token_urlsafe(48),
            file_kek=base64.b64encode(secrets.token_bytes(32)).decode(),
            db_path=REPO_ROOT / "var" / "stegoshare.db",
            storage_path=REPO_ROOT / "var" / "objects",
        ),
        encoding="utf-8",
    )
    ENV_PATH.chmod(0o600)

    print(f"Wrote {ENV_PATH} (mode 600).")
    print("\nNext:")
    print("  set -a && . ./.env && set +a")
    print("  uv run flask --app stegoshare init-db")
    print("  uv run flask --app stegoshare run")
    return 0


def main() -> None:
    raise SystemExit(init())
